import { sqliteTable, text, blob } from 'drizzle-orm/sqlite-core';

export const Cities = sqliteTable('Cities', {
    city_slug: text('city_slug', { length: 1000 }),
    city_name: text('city_name', { length: 1000 }),
    state: text('state', { length: 1000 }),
    meta_title: text('meta_title', { length: 1000 }),
    meta_description: text('meta_description', { length: 1000 }),
    H1: text('H1', { length: 1000 }),
    H2: text('H2', { length: 1000 }),
    sub_heading_text: text('sub_heading_text', { length: 1000 }),
    tick_1: text('tick_1', { length: 1000 }),
    tick_2: text('tick_2', { length: 1000 }),
    tick_3: text('tick_3', { length: 1000 }),
    about_bookphysio: text('about_bookphysio', { length: 1000 }),
});

export const Clinics = sqliteTable('Clinics', {
    'Long Name Version': text('Long Name Version', { length: 1000 }),
    'Typeform registration link': text('Typeform registration link', { length: 1000 }),
    PMS: text('PMS', { length: 1000 }),
    'Meta-title': text('Meta-title', { length: 1000 }),
    'Meta-description': text('Meta-description', { length: 1000 }),
    slug: text('slug', { length: 1000 }),
    Website: text('Website', { length: 1000 }),
    'Clinic Name': text('Clinic Name', { length: 1000 }),
    Display_on_web: text('Display_on_web', { length: 1000 }),
    'link to clinic suburb page': text('link to clinic suburb page', { length: 1000 }),
    'Full Address': text('Full Address', { length: 1000 }),
    City: text('City', { length: 1000 }),
    Suburb: text('Suburb', { length: 1000 }),
    State: text('State', { length: 1000 }),
    Postcode: text('Postcode', { length: 1000 }),
    Email: text('Email', { length: 1000 }),
    Phone: text('Phone', { length: 1000 }),
    nearby1_txt: text('nearby1_txt', { length: 1000 }),
    nearby1_link: text('nearby1_link', { length: 1000 }),
    nearby2_txt: text('nearby2_txt', { length: 1000 }),
    nearby2_link: text('nearby2_link', { length: 1000 }),
    nearby3_txt: text('nearby3_txt', { length: 1000 }),
    nearby3_link: text('nearby3_link', { length: 1000 }),
    nearby4_txt: text('nearby4_txt', { length: 1000 }),
    nearby4_link: text('nearby4_link', { length: 1000 }),
    'About Clinic': text('About Clinic', { length: 1000 }),
});

export const Suburbs = sqliteTable('Suburbs', {
    suburb_slug: text('suburb_slug', { length: 1000 }),
    suburb_name: text('suburb_name', { length: 1000 }),
    City: text('City', { length: 1000 }),
    State: text('State', { length: 1000 }),
    Postcode: text('Postcode', { length: 1000 }),
    meta_title: text('meta_title', { length: 1000 }),
    meta_description: text('meta_description', { length: 1000 }),
    H1: text('H1', { length: 1000 }),
    H2: text('H2', { length: 1000 }),
    about_bookphysio: blob('about_bookphysio'),
    nearby1_link: text('nearby1_link', { length: 1000 }),
    nearby1_txt: text('nearby1_txt', { length: 1000 }),
    nearby1_state: text('nearby1_state', { length: 1000 }),
    nearby1_postcode: text('nearby1_postcode', { length: 1000 }),
    nearby2_link: text('nearby2_link', { length: 1000 }),
    nearby2_txt: text('nearby2_txt', { length: 1000 }),
    nearby2_state: text('nearby2_state', { length: 1000 }),
    nearby2_postcode: text('nearby2_postcode', { length: 1000 }),
    nearby3_link: text('nearby3_link', { length: 1000 }),
    nearby3_txt: text('nearby3_txt', { length: 1000 }),
    nearby3_state: text('nearby3_state', { length: 1000 }),
    nearby3_postcode: text('nearby3_postcode', { length: 1000 }),
    nearby4_link: text('nearby4_link', { length: 1000 }),
    nearby4_txt: text('nearby4_txt', { length: 1000 }),
    nearby4_state: text('nearby4_state', { length: 1000 }),
    nearby4_postcode: text('nearby4_postcode', { length: 1000 }),
});
